global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["gateway:8090"]

  - job_name: "waiting-room"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["waiting-room:8081"]

  - job_name: "catalog"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["catalog:8082"]

  - job_name: "reservation"
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["reservation:8083"]
